name = "paseito"
main = "cloudflare/worker.js"
compatibility_date = "2026-04-20"

[assets]
directory = "./public"
binding = "ASSETS"

[[durable_objects.bindings]]
name = "PASEITO_ROOM"
class_name = "PaseitoRoom"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["PaseitoRoom"]